[package]
name = "open-av"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# yew = "0.19.3"
# wasm-bindgen = "0.2.78"
# gloo = "0.6.0"
wgpu = "0.12.0"
winit = "0.26.1"
env_logger = "*"
pollster = "*"